@localhost = http://localhost:5047
@prod = https://personalbudget.fly.dev

# Select environment: localhost or prod
@HostAddress = {{localhost}}

###
### ============================================
### ACCOUNT ENDPOINTS
### ============================================

###
# Create new user in system
POST {{HostAddress}}/api/authentication/signin
Content-Type: application/json

{
  "Name": "User default",
  "Email": "email@email.com",
  "Password": "Password123@"
}


###
# Login with user in system
POST {{HostAddress}}/api/authentication/login
Content-Type: application/json

{
  "Email": "email@email.com",
  "Password": "Password123@"
}

