@localhost = http://localhost:5047
@prod = https://personalbudget.fly.dev

# Select environment: localhost or prod
@HostAddress = {{localhost}}

# JWT token (cole aqui o token retornado no login)
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmODBmYWQxMi1kMGE1LTRkZWYtODQ0MS0yYTljZTM5ZjFiOWQiLCJleHAiOjE3Njk4MTA4NTEsImlzcyI6IlBlcnNvbmFsQnVkZ2V0IiwiYXVkIjoiUGVyc29uYWxCdWRnZXQuV2ViIn0.0ryZochW23A9eMvbbPCA4jfZgtPwRTwGDjGCQ5pwlOE


### USER ENDPOINTS


###
# Create new user in system
POST {{HostAddress}}/api/authentication/signin
Content-Type: application/json

{
  "Name": "User default",
  "Email": "email@email.com",
  "Password": "Password123@"
}


###
# Login with user in system
POST {{HostAddress}}/api/authentication/login
Content-Type: application/json

{
  "Email": "email@email.com",
  "Password": "Password123@"
}


### ACCOUNT ENDPOINTS


###
# Create new account (requires auth)
POST {{HostAddress}}/api/accounts
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "Bank": "Caixa",
  "Agency": "1301",
  "AccountNumber": "123456-7",
  "InitialBalance": 1005
}


###
# Get all accounts (requires auth)
GET {{HostAddress}}/api/accounts
Authorization: Bearer {{authToken}}
Content-Type: application/json

# ⚠️ Substitua pelo AccountId retornado no GET
@accountId = 0ad31c94-31c0-4f32-b4ff-d37c308d0fa9


### Update Account
PUT {{HostAddress}}/api/accounts/{{accountId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "bank": "Itau",
  "agency": "0002",
  "accountNumber": "654321"
}


### Delete Account
DELETE {{HostAddress}}/api/accounts/{{accountId}}
Authorization: Bearer {{authToken}}


### Category ENDPOINTS


### Create Category of Type Income
POST {{HostAddress}}/api/categories
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "Name": "Food",
  "Type": "Income"
}


### Create Category of Type Expense
POST {{HostAddress}}/api/categories
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "Name": "Food",
  "Type": "Expense"
}


### Get Categories
GET {{HostAddress}}/api/categories
Authorization: Bearer {{authToken}}

# ⚠️ Substitua pelo AccountId retornado no GET
@categoryId = 6fce348d-0f8b-4449-b8e2-9dffcb9cedcb


### Update Category
PUT {{HostAddress}}/api/categories/{{categoryId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "Name": "Food truck",
  "Type": "Income"
}


### Delete Category
DELETE {{HostAddress}}/api/categories/{{categoryId}}
Authorization: Bearer {{authToken}}

# ===============================
# CREDIT CARD
# ===============================


### Create Credit Card
POST {{HostAddress}}/api/credit-cards
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "name": "Visa Platinum",
  "limit": 12000,
  "closingDay": 10,
  "dueDay": 29
}


### Get All Credit Cards
GET {{HostAddress}}/api/credit-cards
Authorization: Bearer {{authToken}}


### Update Credit Card
@creditCardId = 5d083b97-6964-46c3-b918-648f6418fce9

PUT {{HostAddress}}/api/credit-cards/{{creditCardId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Visa Platinum",
  "limit": 3500,
  "closingDay": 5,
  "dueDay": 31
}


### Delete Credit Card
DELETE {{HostAddress}}/api/credit-cards/{{creditCardId}}
Authorization: Bearer {{authToken}}

# ===============================
# TRANSACTIONS
# ===============================

### Create Income (auto complete)
POST {{HostAddress}}/api/transactions
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "categoryId": null,
  "creditCardId": null,
  "type": "Income",
  "paymentMethod": "Account",
  "amount": 5000,
  "date": "2026-01-25",
  "description": "Salary",
  "autoComplete": true
}

### Create Expense (auto complete)
POST {{HostAddress}}/api/transactions
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "categoryId": null,
  "creditCardId": null,
  "type": "Expense",
  "paymentMethod": "Account",
  "amount": 2300,
  "date": "2026-01-25",
  "description": "Salary",
  "autoComplete": true
}


### Create Expense (credit card - pending)
POST {{HostAddress}}/api/transactions
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "AccountId": "{{accountId}}",
  "CategoryId": "{{categoryId}}",
  "CreditCardId": "{{creditCardId}}",
  "type": "Expense",
  "paymentMethod": "CreditCard",
  "amount": 3244,
  "date": "2026-01-25",
  "description": "TV purchase 123",
  "autoComplete": false
}

###
# ⚠️ Substitua pelo TransactionId retornado no GET
@transactionId = b422cb84-1267-4014-b032-9b0525bcca2e

### Get Transactions by Account
GET {{HostAddress}}/api/transactions/account/{{accountId}}
Authorization: Bearer {{authToken}}

### Complete Transaction (ex: pay credit card)
POST {{HostAddress}}/api/transactions/{{transactionId}}/complete
Authorization: Bearer {{authToken}}

### Cancel Transaction
POST {{HostAddress}}/api/transactions/{{transactionId}}/cancel
Authorization: Bearer {{authToken}}

